apiVersion: v1
kind: ConfigMap
metadata:
  namespace: analytics
  name: spark-defaults
data:
  spark-defaults.conf: |-
    spark.master spark://sparkmaster:7077
    spark.driver.extraLibraryPath /etc/hadoop/lib/native
    spark.driver.extraClassPath /etc/spark/jars/hadoop-aws-2.7.0.jar:/opt/spark/jars/aws-java-sdk-1.7.4.jar
    #spark.hadoop.fs.s3a.impl org.apache.hadoop.fs.s3a.S3AFileSystem
    #spark.fs.s3a.connection.ssl.enabled true
    #spark.executor.extraJavaOptions -Dcom.amazonaws.sdk.disableCertChecking=1
    spark.app.id KubernetesSpark
    spark.eventLog.dir /etc/spark/logs
    spark.history.fs.logDirectory /etc/spark/spark-history
    spark.deploy.recoveryMode ZOOKEEPER
    spark.deploy.zookeeper.url zk-svc:2181
    spark.deploy.zookeeper.dir /var/lib/zookeeper
